# Generated by Django 4.1.1 on 2022-11-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pneumonia_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Patient_X_Ray_Heatmap',
            field=models.CharField(max_length=100),
        ),
    ]
