# Generated by Django 4.1.1 on 2022-11-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pneumonia_App', '0002_alter_patient_patient_x_ray_heatmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Patient_X_Ray_Heatmap',
            field=models.FileField(upload_to=''),
        ),
    ]
