# Generated by Django 4.1.1 on 2022-11-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pneumonia_App', '0004_patient_patientgender_patient_patientremark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='PatientGender',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PatientRemark',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PatientStatus',
            field=models.CharField(max_length=20),
        ),
    ]
